export enum USER_TYPES {
    USER = 2,
    ADMIN = 0,
    TECHNICAL = 3,
    WAREHOUSE = 4

};
export enum CONSTANTS_MAX {
    EMPLOYEE_ID_LEN = 10,
    NAME_LEN = 50,
    EMAIL_LEN = 100,
    FEEDBACK_LEN = 200,
    DEPARMENT_LEN = 20,
    CATEGORY_LEN = 20
}

export enum CONSTANTS_MIN {
    PASSWORD_LEN = 6,
    NAME_LEN = 5,
    DEPARMENT_LEN = 3,
    CATEGORY_LEN = 2

}
export enum PAGE_SIZE {
    PAGE_USER = 20,
    PAGE_LOCATION = 20,
    PAGE_CATEGORY = 20,
    PAGE_DEVICE = 20,
    PAGE_USAGE = 20,
    PAGE_MATERIAL = 20,
}
export enum DEVICE_STATUS {
    ACTIVE,
    INACTIVE,
    REPAIR,
    DECOMMISSIONED,
}